name: php-fpm Docker Image

on:
  push:
    branches:
      - main
      - 'releases/**'
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 0 0 * * *

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update

    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Login To Alibaba Cloud Container Registry
      run: |
        echo ${{ secrets.ALIYUN_PWD }} | docker login -u ${{ secrets.ALIYUN_USERNAME }} --password-stdin registry.cn-shenzhen.aliyuncs.com

    - name: Build Docker
      run: |
        docker build -t php -f 8.1/Dockerfile .

    - name: Build & Push Multiarch Image
      run: |
        docker image tag php ${{ secrets.DOCKERHUB_USERNAME }}/php:latest
        docker image tag php ${{ secrets.DOCKERHUB_USERNAME }}/php:8-fpm-alpine
        docker image tag php registry.cn-shenzhen.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/php:latest
        docker image tag php registry.cn-shenzhen.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/php:8-fpm-alpine
        docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/php
        docker image push --all-tags registry.cn-shenzhen.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/php
